// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantApi.Data;

#nullable disable

namespace RestaurantApi.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    partial class RestaurantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("RestaurantApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "Promotions"
                        },
                        new
                        {
                            Id = -2,
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = -3,
                            Name = "Bowl"
                        },
                        new
                        {
                            Id = -4,
                            Name = "Cheeseburger"
                        },
                        new
                        {
                            Id = -5,
                            Name = "Salad"
                        },
                        new
                        {
                            Id = -6,
                            Name = "Breakfast"
                        },
                        new
                        {
                            Id = -7,
                            Name = "Drinks"
                        },
                        new
                        {
                            Id = -8,
                            Name = "Soup"
                        },
                        new
                        {
                            Id = -9,
                            Name = "Dessert"
                        });
                });

            modelBuilder.Entity("RestaurantApi.Models.CategorySelectionGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<int>("SelectionGroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("selection_group_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SelectionGroupId");

                    b.ToTable("category_selection_groups", (string)null);
                });

            modelBuilder.Entity("RestaurantApi.Models.CustomerInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment")
                        .HasAnnotation("Relational:JsonPropertyName", "comment");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name")
                        .HasAnnotation("Relational:JsonPropertyName", "firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name")
                        .HasAnnotation("Relational:JsonPropertyName", "lastName");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone")
                        .HasAnnotation("Relational:JsonPropertyName", "phone");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("customer_info", (string)null);
                });

            modelBuilder.Entity("RestaurantApi.Models.DeliveryAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bell")
                        .HasColumnType("TEXT")
                        .HasColumnName("bell");

                    b.Property<string>("Door")
                        .HasColumnType("TEXT")
                        .HasColumnName("door");

                    b.Property<string>("House")
                        .HasColumnType("TEXT")
                        .HasColumnName("house");

                    b.Property<int>("PostcodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("postcode_id");

                    b.Property<string>("Stairs")
                        .HasColumnType("TEXT")
                        .HasColumnName("stairs");

                    b.Property<string>("Stick")
                        .HasColumnType("TEXT")
                        .HasColumnName("stick");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("street");

                    b.HasKey("Id");

                    b.HasIndex("PostcodeId");

                    b.ToTable("delivery_addresses", (string)null);
                });

            modelBuilder.Entity("RestaurantApi.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CategoryId = -1,
                            Description = "Get a pizza and drink at a special price!",
                            ImageUrl = "/images/categories/promotionsCategory.png",
                            Name = "Special Combo",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = -2,
                            CategoryId = -1,
                            Description = "Perfect for the whole family - 2 pizzas and 4 drinks",
                            ImageUrl = "/images/categories/promotionsCategory.png",
                            Name = "Family Bundle",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 1,
                            CategoryId = -7,
                            Description = "Classic carbonated soft drink",
                            Name = "Cola",
                            Price = 4m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = -5,
                            Description = "Salad with fresh vegetables and cheese",
                            ImageUrl = "https://restaurant-images33.s3.eu-north-1.amazonaws.com/salad.jpg",
                            Name = "Salad",
                            Price = 8m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = -2,
                            Description = "A delightful plant-based pizza with a variety of fresh toppings",
                            ImageUrl = "https://restaurant-images33.s3.eu-north-1.amazonaws.com/veganpizza.jpg",
                            Name = "Vegan Pizza",
                            Price = 12m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = -3,
                            Description = "Filled with fresh ingredients, perfect for a healthy and satisfying meal.",
                            ImageUrl = "https://restaurant-images33.s3.eu-north-1.amazonaws.com/bowll.jpg",
                            Name = "Bowl",
                            Price = 10m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = -7,
                            Description = "Pure, crisp, and refreshing still water",
                            Name = "Water",
                            Price = 1m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = -7,
                            Description = "Traditional Turkish yogurt-based drink, cool and refreshing with a creamy texture",
                            Name = "Ayran",
                            Price = 2m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = -7,
                            Description = "A light, refreshing lemon-lime soda with a crisp, bubbly taste to quench your thirst",
                            Name = "Sprite",
                            Price = 3m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = -2,
                            Description = "Classic pizza with rich tomato sauce, fresh mozzarella, and basil",
                            ImageUrl = "https://restaurant-images33.s3.eu-north-1.amazonaws.com/margarita.jpg",
                            Name = "Margarita Pizza",
                            Price = 9m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = -7,
                            Description = "A premium Turkish soda, light and refreshing, perfect for pairing with your meal.",
                            Name = "Soda",
                            Price = 2m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = -4,
                            Description = "A delicious burger made with a juicy beef patty, crispy bacon, melted cheese, and fresh onions, all nestled in a soft bun",
                            ImageUrl = "https://restaurant-images33.s3.eu-north-1.amazonaws.com/baconburger.jpg",
                            Name = "Baconburger",
                            Price = 6m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = -4,
                            Description = "Classic American cheeseburger",
                            ImageUrl = "https://restaurant-images33.s3.eu-north-1.amazonaws.com/cheeseburger.jpg",
                            Name = "Cheeseburger",
                            Price = 7m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = -5,
                            Description = "A healthy salad with grilled chicken, fresh veggies, and dressing",
                            ImageUrl = "https://restaurant-images33.s3.eu-north-1.amazonaws.com/chickensalad.jpg",
                            Name = "Chicken Salad",
                            Price = 9m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = -2,
                            Description = "A savory pizza topped with grilled chicken and fresh vegetables",
                            ImageUrl = "https://restaurant-images33.s3.eu-north-1.amazonaws.com/chickenpizza.jpg",
                            Name = "Chicken Pizza",
                            Price = 10m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = -2,
                            Description = "A flavorful pizza with spicy sausage and cheese",
                            ImageUrl = "https://restaurant-images33.s3.eu-north-1.amazonaws.com/sausagepizza.jpg",
                            Name = "Sausage Pizza",
                            Price = 10m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = -6,
                            Description = "A delicious breakfast with bacon, eggs, and fresh vegetables",
                            ImageUrl = "https://restaurant-images33.s3.eu-north-1.amazonaws.com/baconbreakfast.jpg",
                            Name = "Bacon Breakfast Menu",
                            Price = 12m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = -8,
                            Description = "Spicy, sweet, and fragrant with lemongrass, lime, and tender chicken",
                            ImageUrl = "https://restaurant-images33.s3.eu-north-1.amazonaws.com/thaisoup.jpg",
                            Name = "Thai Coconut Chicken Soup",
                            Price = 7m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = -8,
                            Description = "Rich, earthy, and velvety with sautéed mushrooms and a hint of garlic",
                            ImageUrl = "https://restaurant-images33.s3.eu-north-1.amazonaws.com/mushroomsoup.jpg",
                            Name = "Creamy Wild Mushroom Soup",
                            Price = 6m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = -8,
                            Description = "Smooth, tangy, and topped with a swirl of cream and fresh basil",
                            ImageUrl = "https://restaurant-images33.s3.eu-north-1.amazonaws.com/tomatosoup.jpg",
                            Name = "Roasted Tomato Basil Soup",
                            Price = 6m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = -9,
                            Description = "Warm, gooey center served with a scoop of vanilla ice cream",
                            ImageUrl = "https://restaurant-images33.s3.eu-north-1.amazonaws.com/moltendessert.jpg",
                            Name = "Molten Chocolate Lava Cake",
                            Price = 5m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = -9,
                            Description = "Zesty lemon curd topped with pillowy toasted meringue in a buttery crust",
                            ImageUrl = "https://restaurant-images33.s3.eu-north-1.amazonaws.com/lemontartdessert.jpg",
                            Name = "Lemon Meringue Tart",
                            Price = 5m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = -9,
                            Description = "Layers of fluffy cake, whipped cream, and fresh strawberries",
                            ImageUrl = "https://restaurant-images33.s3.eu-north-1.amazonaws.com/strawberrydessert.jpg",
                            Name = "Strawberry Shortcake Parfait",
                            Price = 6m
                        });
                });

            modelBuilder.Entity("RestaurantApi.Models.ItemAllergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllergenCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("allergen_code");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("item_allergens", (string)null);
                });

            modelBuilder.Entity("RestaurantApi.Models.ItemIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<bool>("CanExclude")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_exclude");

                    b.Property<decimal>("ExtraCost")
                        .HasColumnType("TEXT")
                        .HasColumnName("extra_cost");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_mandatory");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("item_ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanExclude = false,
                            ExtraCost = 0m,
                            IsMandatory = false,
                            ItemId = 3,
                            Name = "Dough"
                        },
                        new
                        {
                            Id = 2,
                            CanExclude = false,
                            ExtraCost = 0m,
                            IsMandatory = false,
                            ItemId = 3,
                            Name = "Tomato Sauce"
                        },
                        new
                        {
                            Id = 3,
                            CanExclude = false,
                            ExtraCost = 0m,
                            IsMandatory = false,
                            ItemId = 3,
                            Name = "Mozzarella"
                        },
                        new
                        {
                            Id = 4,
                            CanExclude = false,
                            ExtraCost = 0m,
                            IsMandatory = false,
                            ItemId = 3,
                            Name = "Basil"
                        });
                });

            modelBuilder.Entity("RestaurantApi.Models.ItemOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<int>("OfferId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("offer_id");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OfferId");

                    b.ToTable("item_offers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemId = 3,
                            OfferId = 1
                        },
                        new
                        {
                            Id = 2,
                            ItemId = 8,
                            OfferId = 1
                        },
                        new
                        {
                            Id = 3,
                            ItemId = 13,
                            OfferId = 1
                        },
                        new
                        {
                            Id = 4,
                            ItemId = 14,
                            OfferId = 1
                        });
                });

            modelBuilder.Entity("RestaurantApi.Models.ItemSelectionGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<int>("SelectionGroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("selection_group_id");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("SelectionGroupId");

                    b.ToTable("item_selection_groups", (string)null);
                });

            modelBuilder.Entity("RestaurantApi.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("TEXT")
                        .HasColumnName("discount_percentage");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("offers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "20% off on all pizzas",
                            DiscountPercentage = 20.0m,
                            EndDate = "2025-05-21 14:32:26.987536",
                            IsActive = true,
                            Name = "Happy Hour",
                            StartDate = "2025-04-21 14:32:26.987483"
                        },
                        new
                        {
                            Id = 2,
                            Description = "15% off with student ID",
                            DiscountPercentage = 15.0m,
                            EndDate = "2025-07-20 14:32:26.987655",
                            IsActive = true,
                            Name = "Student Discount",
                            StartDate = "2025-04-21 14:32:26.987655"
                        });
                });

            modelBuilder.Entity("RestaurantApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("CustomerInfoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("customer_info_id");

                    b.Property<string>("OrderMethod")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("order_method");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("order_number");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_method");

                    b.Property<string>("SpecialNotes")
                        .HasColumnType("TEXT")
                        .HasColumnName("special_notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("stripe_session_id");

                    b.Property<string>("Total")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("total");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("id");

                    b.HasIndex("CustomerInfoId");

                    b.HasIndex("UserId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("RestaurantApi.Models.OrderLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_id");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("RestaurantApi.Models.Postcode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("district");

                    b.HasKey("Id");

                    b.ToTable("postcodes", (string)null);
                });

            modelBuilder.Entity("RestaurantApi.Models.PostcodeMinimumOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinimumOrderValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PostcodeMinimumOrders");
                });

            modelBuilder.Entity("RestaurantApi.Models.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("TEXT")
                        .HasColumnName("discount_percentage");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<decimal>("DisplayPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("display_price");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBundle")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_bundle");

                    b.Property<int?>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("promotions", (string)null);
                });

            modelBuilder.Entity("RestaurantApi.Models.SelectionGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_required");

                    b.Property<int>("MaxSelect")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_select");

                    b.Property<int>("MinSelect")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_select");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Threshold")
                        .HasColumnType("INTEGER")
                        .HasColumnName("threshold");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("selection_groups", (string)null);
                });

            modelBuilder.Entity("RestaurantApi.Models.SelectionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<int>("SelectionGroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("selection_group_id");

                    b.HasKey("Id");

                    b.HasIndex("SelectionGroupId");

                    b.ToTable("selection_options", (string)null);
                });

            modelBuilder.Entity("RestaurantApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT")
                        .HasColumnName("Address");

                    b.Property<string>("Bell")
                        .HasColumnType("TEXT")
                        .HasColumnName("Bell");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("Comment");

                    b.Property<string>("Door")
                        .HasColumnType("TEXT")
                        .HasColumnName("Door");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("FirstName");

                    b.Property<string>("House")
                        .HasColumnType("TEXT")
                        .HasColumnName("House");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LastName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Password");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("Phone");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("PostalCode");

                    b.Property<string>("Stairs")
                        .HasColumnType("TEXT")
                        .HasColumnName("Stairs");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RestaurantApi.Models.CategorySelectionGroup", b =>
                {
                    b.HasOne("RestaurantApi.Models.Category", "Category")
                        .WithMany("CategorySelectionGroups")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantApi.Models.SelectionGroup", "SelectionGroup")
                        .WithMany("CategorySelectionGroups")
                        .HasForeignKey("SelectionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("SelectionGroup");
                });

            modelBuilder.Entity("RestaurantApi.Models.CustomerInfo", b =>
                {
                    b.OwnsOne("RestaurantApi.Models.Address", "Address", b1 =>
                        {
                            b1.Property<int>("CustomerInfoId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Bell")
                                .HasColumnType("TEXT")
                                .HasColumnName("bell")
                                .HasAnnotation("Relational:JsonPropertyName", "bell");

                            b1.Property<string>("Door")
                                .HasColumnType("TEXT")
                                .HasColumnName("door")
                                .HasAnnotation("Relational:JsonPropertyName", "door");

                            b1.Property<string>("House")
                                .HasColumnType("TEXT")
                                .HasColumnName("house")
                                .HasAnnotation("Relational:JsonPropertyName", "house");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("TEXT")
                                .HasColumnName("postal_code")
                                .HasAnnotation("Relational:JsonPropertyName", "postalCode");

                            b1.Property<string>("Stairs")
                                .HasColumnType("TEXT")
                                .HasColumnName("stairs")
                                .HasAnnotation("Relational:JsonPropertyName", "stairs");

                            b1.Property<string>("Stick")
                                .HasColumnType("TEXT")
                                .HasColumnName("stick")
                                .HasAnnotation("Relational:JsonPropertyName", "stick");

                            b1.Property<string>("Street")
                                .HasColumnType("TEXT")
                                .HasColumnName("street")
                                .HasAnnotation("Relational:JsonPropertyName", "street");

                            b1.HasKey("CustomerInfoId");

                            b1.ToTable("customer_info");

                            b1.HasAnnotation("Relational:JsonPropertyName", "address");

                            b1.WithOwner()
                                .HasForeignKey("CustomerInfoId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("RestaurantApi.Models.DeliveryAddress", b =>
                {
                    b.HasOne("RestaurantApi.Models.Postcode", "Postcode")
                        .WithMany("DeliveryAddresses")
                        .HasForeignKey("PostcodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postcode");
                });

            modelBuilder.Entity("RestaurantApi.Models.Item", b =>
                {
                    b.HasOne("RestaurantApi.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RestaurantApi.Models.ItemAllergen", b =>
                {
                    b.HasOne("RestaurantApi.Models.Item", "Item")
                        .WithMany("ItemAllergens")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("RestaurantApi.Models.ItemIngredient", b =>
                {
                    b.HasOne("RestaurantApi.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("RestaurantApi.Models.ItemOffer", b =>
                {
                    b.HasOne("RestaurantApi.Models.Item", "Item")
                        .WithMany("ItemOffers")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantApi.Models.Offer", "Offer")
                        .WithMany("ItemOffers")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("RestaurantApi.Models.ItemSelectionGroup", b =>
                {
                    b.HasOne("RestaurantApi.Models.Item", "Item")
                        .WithMany("ItemSelectionGroups")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantApi.Models.SelectionGroup", "SelectionGroup")
                        .WithMany("ItemSelectionGroups")
                        .HasForeignKey("SelectionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("SelectionGroup");
                });

            modelBuilder.Entity("RestaurantApi.Models.Order", b =>
                {
                    b.HasOne("RestaurantApi.Models.CustomerOrderInfo", "CustomerInfo")
                        .WithMany()
                        .HasForeignKey("CustomerInfoId");

                    b.HasOne("RestaurantApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("CustomerInfo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantApi.Models.OrderLineItem", b =>
                {
                    b.HasOne("RestaurantApi.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantApi.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantApi.Models.Promotion", b =>
                {
                    b.HasOne("RestaurantApi.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Item");
                });

            modelBuilder.Entity("RestaurantApi.Models.SelectionOption", b =>
                {
                    b.HasOne("RestaurantApi.Models.SelectionGroup", "SelectionGroup")
                        .WithMany("Options")
                        .HasForeignKey("SelectionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SelectionGroup");
                });

            modelBuilder.Entity("RestaurantApi.Models.Category", b =>
                {
                    b.Navigation("CategorySelectionGroups");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("RestaurantApi.Models.Item", b =>
                {
                    b.Navigation("ItemAllergens");

                    b.Navigation("ItemOffers");

                    b.Navigation("ItemSelectionGroups");
                });

            modelBuilder.Entity("RestaurantApi.Models.Offer", b =>
                {
                    b.Navigation("ItemOffers");
                });

            modelBuilder.Entity("RestaurantApi.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("RestaurantApi.Models.Postcode", b =>
                {
                    b.Navigation("DeliveryAddresses");
                });

            modelBuilder.Entity("RestaurantApi.Models.SelectionGroup", b =>
                {
                    b.Navigation("CategorySelectionGroups");

                    b.Navigation("ItemSelectionGroups");

                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
